services:
  build:
    image: ghcr.io/go-testings/go-ethereum_alltools:master
    pull_policy: always
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"

    volumes:
      - node-data:/data
    command: >
      geth
      --datadir=/data
      --syncmode=full
      --cache=1024
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=${RPC_API:-eth,net,web3,debug,admin}
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.api=${WS_API:-eth,net,web3,debug}
      --nodiscover
    networks:
      - go-ethereum-network

volumes:
  node-data:
    driver: local

networks:
  go-ethereum-network:
    driver: bridge
